//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketMatchProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CricketEntities : DbContext
    {
        public CricketEntities()
            : base("name=CricketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Match> Matches { get; set; }
        public DbSet<Player_Match_Mapping> Player_Match_Mapping { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<PlayerType> PlayerTypes { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}
