//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketMatchProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Match
    {
        public Match()
        {
            this.Player_Match_Mapping = new HashSet<Player_Match_Mapping>();
        }
    
        public int Id { get; set; }
        public string Match_Name { get; set; }
        public string Match_Date { get; set; }
        public Nullable<int> Team_One { get; set; }
        public Nullable<int> Team_Two { get; set; }
        public string Start_Time { get; set; }
        public string Address { get; set; }


    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual ICollection<Player_Match_Mapping> Player_Match_Mapping { get; set; }
    }
}
