//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketMatchProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_Match_Mapping
    {
        public int id { get; set; }
        public Nullable<int> MatchId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> PlayerTypeId { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
        public virtual PlayerType PlayerType { get; set; }
        public virtual Team Team { get; set; }
    }
}
