//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketMatchProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Matches = new HashSet<Match>();
            this.Matches1 = new HashSet<Match>();
            this.Player_Match_Mapping = new HashSet<Player_Match_Mapping>();
        }
    
        public int Id { get; set; }
        public string Team_Name { get; set; }
    
        public virtual ICollection<Match> Matches { get; set; }
        public virtual ICollection<Match> Matches1 { get; set; }
        public virtual ICollection<Player_Match_Mapping> Player_Match_Mapping { get; set; }
    }
}
